### ISSUE TITLE
White version

### ISSUE THREAD

**Issue by adius** [iconic/open-iconic#1]
It would be cool if you could also provide a white version of the icons! Do you think that's possible? =)

**Comment by adius** [comment]
FYI: If you have imagemagick installed you can simply run `mogrify -negate *.png` in the png folder to get the png icons in white…

**Comment by somerandomdude** [comment]
Would you be interested in doing this and sending a pull request?

**Comment by adius** [comment]
Mh… I'd rather write some kind of build script to automate the process and add the possibility to compile the icon-set in any color. However, I'm not sure whether this is outside of the scope of this project as it would compete with your commercial version of iconic and I guess you don't want to weaken your selling point, right? ;-)

**Comment by somerandomdude** [comment]
It won't compete with Iconic at all - no need to worry about that. We agree, this is better taken on through automation. We'd prefer to package Open Iconic with one color for the PNGs and let people generate new versions based on their individual needs.
