### ISSUE TITLE
Do we need to add svg on cdnjs

### ISSUE THREAD

**Issue by kennynaoh** [iconic/open-iconic#25]
Hello @somerandomdude , I am the member of cdnjs project. We want to host this library. There is a question want to ask. I want to confirm that do I need to add all files under `svg/` and `open-iconic.svg`, `open-iconic.min.svg` under `sprite/`. Thanks!

https://github.com/cdnjs/cdnjs/issues/9222
https://github.com/cdnjs/cdnjs/pull/10224

**Comment by somerandomdude** [comment]
Hey Kenny - yes all the files are needed. Thanks!

**Comment by kennynaoh** [comment]
Thank you
