### ISSUE TITLE
SSL certificate for https://useiconic.com is out of date

### ISSUE THREAD

**Issue by dotboris** [iconic/open-iconic#26]
When I try to access <https://useiconic.com> I get an SSL error saying that the certificate is expired. 

The certificate states that it will expire after `Thursday, April 27, 2017 at 7:59:59 PM GMT-04:00`.

I can't even access the HTTP site since it redirects me to the HTTPS version which has an expired certificate.

**Comment by dotboris** [comment]
Looks like this is fixed

**Comment by runoncedev** [comment]
It's happening again. Certificate expired at Monday, July 2, 2018 at 5:55:42 PM.

**Comment by benjefferies** [comment]
It's that time of year again 😄. It might be worth checking out https://github.com/caddyserver/caddy as a webserver?
