### ISSUE TITLE
Please clarify the difference between Open Iconic and Iconic

### ISSUE THREAD

**Issue by simevidas** [iconic/open-iconic#3]
The Open Iconic page (https://useiconic.com/open) says: 

> If you're not ready for Iconic (yet), this is the next best stop.

This doesn't tell me much. I can't know if I'm "ready" for Iconic if I don't know the difference :)

**Comment by somerandomdude** [comment]
Good question. Open Iconic is a great basic icon set, but doesn't have any of the advanced features laid out in [Iconic's tour](https://useiconic.com/tour) - specifically three levels of fidelity for each icon, styling an icon's details, responsiveness or smart features. Let me know if that makes sense.

**Comment by simevidas** [comment]
@somerandomdude Got it. Thanks :)
