### ISSUE TITLE
please change name. perhaps typo name ellipses, correct name is ellipsis

### ISSUE THREAD

**Issue by mitsuhisaT** [iconic/open-iconic#36]
I think ellipses is wrong name, correct name is 'ellipsis'.

**Comment by BrekiTomasson** [comment]
"ellipses" is the plural of "ellipsis".

**Comment by mitsuhisaT** [comment]
I thinked ellipses is plural of ellipse.
I understand same spelling ellipses that are plural for ellipsis and ellipse.
