### ISSUE TITLE
Can't resize through bootstrap file

### ISSUE THREAD

**Issue by blachawk** [iconic/open-iconic#37]
I'm currently working through a Bootstrap 4 project:
I have the following iconic style-sheet linked within the `<head>` of my page:
```
<link rel="stylesheet" href="/../inc/icons/open-iconic/font/css/open-iconic-bootstrap.css" >
```
and using a briefcase icon like so...
```
<span class="oi oi-briefcase"></span>
```
I now see the icon on my page, but in my .scss file, the following has no impact on sizing the icon larger...

```
   .oi-briefcase {
            width:50px;
            height:50px;
        }
```
Through developer tools in Chrome, I can see that it's applied to the element and nothing is overriding it. What am I doing wrong or missing?

**Comment by IonutArhire** [comment]
It should work if you modify the font-size property instead of trying to modify the size.
