### ISSUE TITLE
useiconic.com - SSL expired

### ISSUE THREAD

**Issue by HZ-labs** [iconic/open-iconic#40]
useiconic.com uses an invalid security certificate. The certificate expired on July 2, 2018

**Comment by tinterweb** [comment]
Any update on this? We cant add CC details to an insecure page 👎

**Comment by pparidans** [comment]
Probably forgotten to set an auto renewal of the Let's Encrypt certificate...

Anyone there?

**Comment by bastones** [comment]
Tick, tock.

**Comment by mingtsay** [comment]
Ping. This issue shouldn't place without any matter.

**Comment by textpain** [comment]
Confirmed!

**Comment by sascha-schieferdecker** [comment]
Confirmed, annoying.

**Comment by Acrunam** [comment]
This issue has recurred for me. Maybe their certificate has run out again?
