### ISSUE TITLE
Excess 1px used to bootstrap 

### ISSUE THREAD

**Issue by TomVista** [iconic/open-iconic#43]
bootstrap v4
openIcon v1.1.1
<div class="form-group bg-primary d-flex justify-content-between">
        <span id="Controls" class=" d-block oi oi-target"></span>
        <div class="d-flex">
            <span class=" d-block oi oi-minus"></span>
            <span class=" d-block oi oi-browser"></span>
            <span class=" d-block oi oi-x"></span>
        </div>
</div>

**Comment by TomVista** [comment]
`<div` class="form-group bg-primary d-flex justify-content-between">
        <span id="Controls" class=" d-block oi oi-target"></span>
        <div class="d-flex">
            <span class=" d-block oi oi-minus"></span>
            <span class=" d-block oi oi-browser"></span>
            <span class=" d-block oi oi-x"></span>
        </div>

    </div>

**Comment by TomVista** [comment]
`<div class="form-group bg-primary d-flex justify-content-between">
        <span id="Controls" class=" d-block oi oi-target"></span>
        <div class="d-flex">
            <span class=" d-block oi oi-minus"></span>
            <span class=" d-block oi oi-browser"></span>
            <span class=" d-block oi oi-x"></span>
        </div>

    </div>`

**Comment by TomVista** [comment]
`<div class="form-group bg-primary d-flex justify-content-between"><span id="Controls" class=" d-block oi oi-target "></span><div class="d-flex"> <span class=" d-block oi oi-minus"></span><span class=" d-block oi oi-browser "></span> <span class=" d-block oi oi-x "></span> </div></div>`

**Comment by KlomDark** [comment]
See #34

**Comment by TomVista** [comment]
@KlomDark  get,thank you
