### ISSUE TITLE
IE 11 - no icons to view

### ISSUE THREAD

**Issue by Otto404** [iconic/open-iconic#6]
![icon-error](https://cloud.githubusercontent.com/assets/3367832/3963886/0bba75bc-2782-11e4-8d9d-669b2ca5582a.jpg)

see the attached file: you will see, that's nothing to see...

**Comment by protodave** [comment]
Ah yes, good catch, thanks! The icons are fine, but the specific technique we are using to display the icons on that demo page (SVG `use` tag with external source reference) isn't supported in IE 9/10/11. Fixing that now...

**Comment by somerandomdude** [comment]
Hi Otto, we've fixed this. Thanks!

**Comment by Otto404** [comment]
Super! Great.

Gesendet von meinem Windows Phone

---

Von: P.J. Onori
Gesendet: 19.08.2014 20:01
An: iconic/open-iconic
Cc: Otto404
Betreff: Re: [open-iconic] IE 11 - no icons to view (#6)

Hi Otto, we've fixed this. Thanks!

---
