### ISSUE TITLE
issue with x svg

### ISSUE THREAD

**Issue by neo-inuit** [iconic/open-iconic#7]
The x.svg seems weird

**Comment by somerandomdude** [comment]
What about it seems weird?

**Comment by neo-inuit** [comment]
![x_look_weird](https://cloud.githubusercontent.com/assets/5813418/3970610/3375d00c-27cc-11e4-83df-0050467ef82e.png)

But other one too, it's seems like its only on my computer.

**Comment by somerandomdude** [comment]
Oh, wow. Yeah, that's weird. What browser/OS are you using to see this? Could you send us a URL so we could replicate?

**Comment by neo-inuit** [comment]
It 's just an issue with the image viewer software, and the preview with nautilus, it's working well with inkscape

**Comment by neo-inuit** [comment]
i m running on fedora 19

**Comment by somerandomdude** [comment]
Ah, I see. OK, well it's probably not on our end. If it's not breaking in any browser and just the eccentricities of this specific image viewer, I think it's safe close this for now. 

Thanks for the catch nonetheless!
